# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS_base_Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Moya'
  
  # Pods for iOS_base_Swift

  target 'iOS_base_SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS_base_SwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
